language: ruby
rvm:
  - 2.3.0
cache: bundler
sudo: false
env:
  - RAILS_ENV=test
before_install: gem install bundler -v 1.11.2
before_script: bin/rake db:migrate
script: bin/test
deploy:
  provider: rubygems
  api_key:
    secure: uWgUbc6bOwkfxh9t/V4Epw7OHvA69A3EGlVV63DX3kX1l8MaNqbxo3BO1RJHNSZH8TgBZdUosWpBur3SI8Fi+FL22KWaJ/Q4pz0XEqbeq9L6iDa8ww3L6HD9efa0EhrPvju+pIi5wXCk9jCsdnzoo2wzwKapd9fSBoF5u606sU1mlX/n0OCh6/M2+0XhryaLiIAVyyNVRBm4PGveZqdzPrxLijuMvvEwxynSADt2R1LZVqe0xi+oCvIl+KmTWfRyVCffpn7G3kerJzHfgH1lccngDFMLJqqRpWhDSthkH9OwjQh9CYtcnkBayXhTIP7vg8V7ZlOzyvo2T//poXP1AMmggFhd/ISYjm4n93wCucV6tIE0dBNoYHlS16G0Qx+W87fv1g9fwL4ryVh+CgowgoIxMXdvplbSbuFK6aZ9AUeYJ7fZaxMVh664yxeAHrsUarwBUSpZqDK05pxNZnQYjSVbQ4XbiPsKX8Q4ud8iUMJe+8f9wFr0OqYVBZqcv5BlSzoCo5p1DEQ2groEh4vWcFmEfn5O3qFSIoOzDNTlgOqa5tvUO5FPVG7r2AkFY/M5WpwbCH1ndJ28VBydAtlAtgLCxjze9Dk7l0WgOnXd1XQ9btge1xz4lMM78W/25WjBM2Gtpgu8PC2U5K5s2hE7nsk9mKzTm4dbNoNNWmNhKac=
  gem: halt
  on:
    tags: true
    repo: tubbo/halt
